const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const configRoot = path.join(repoRoot, "src", "config", "sierpinski");
const outputPath = path.join(configRoot, "registry.generated.ts");

function walkYamlFiles(dir, files = []) {
  for (const name of fs.readdirSync(dir)) {
    const fullPath = path.join(dir, name);
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory()) {
      walkYamlFiles(fullPath, files);
      continue;
    }

    if (/\.ya?ml$/i.test(name)) {
      files.push(fullPath);
    }
  }

  return files;
}

const files = walkYamlFiles(configRoot).sort();

let output = "/* Auto-generated by scripts/generate_sierpinski_registry.js. Do not edit by hand. */\n\n";
output += "export interface SierpinskiRegistryEntry {\n";
output += "  path: string;\n";
output += "  yamlSource: string;\n";
output += "}\n\n";
output += "const registry: Record<string, SierpinskiRegistryEntry> = {\n";

for (const filePath of files) {
  const relativePath = path.relative(configRoot, filePath).split(path.sep).join("/");
  const yamlSource = fs.readFileSync(filePath, "utf8");
  output += `  ${JSON.stringify(relativePath)}: {\n`;
  output += `    path: ${JSON.stringify(relativePath)},\n`;
  output += `    yamlSource: ${JSON.stringify(yamlSource)}\n`;
  output += "  },\n";
}

output += "};\n\n";
output += "export function getSierpinskiYamlSource(relativePath: string): string {\n";
output += "  const normalizedPath = relativePath.replace(/^\\/+/, \"\");\n";
output += "  const entry = registry[normalizedPath];\n";
output += "  if (!entry) {\n";
output += "    throw new Error(\"Unknown Sierpinski YAML file: \" + normalizedPath);\n";
output += "  }\n";
output += "  return entry.yamlSource;\n";
output += "}\n\n";
output += "export function listSierpinskiYamlPaths(): string[] {\n";
output += "  return Object.keys(registry);\n";
output += "}\n";

fs.writeFileSync(outputPath, output);
console.log(`Wrote ${path.relative(repoRoot, outputPath)} with ${files.length} YAML files.`);
